/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 100131
 Source Host           : localhost:3306
 Source Schema         : dbsscpd_bartim

 Target Server Type    : MySQL
 Target Server Version : 100131
 File Encoding         : 65001

 Date: 10/08/2021 15:18:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for desa
-- ----------------------------
DROP TABLE IF EXISTS `desa`;
CREATE TABLE `desa`  (
  `desa_id` int(11) NOT NULL AUTO_INCREMENT,
  `nm_desa` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `kec_id` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`desa_id`) USING BTREE,
  INDEX `subkategori_kategori_id`(`kec_id`) USING BTREE,
  CONSTRAINT `desa_ibfk_1` FOREIGN KEY (`kec_id`) REFERENCES `kecamatan` (`kec_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 109 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of desa
-- ----------------------------
INSERT INTO `desa` VALUES (1, '-', 1);
INSERT INTO `desa` VALUES (3, ' PULAU PATAI', 1);
INSERT INTO `desa` VALUES (4, ' SARAPAT', 1);
INSERT INTO `desa` VALUES (5, ' MAGANTIS', 1);
INSERT INTO `desa` VALUES (6, ' JA\'AR', 1);
INSERT INTO `desa` VALUES (7, ' MATABU', 1);
INSERT INTO `desa` VALUES (8, ' DORONG', 1);
INSERT INTO `desa` VALUES (9, ' DIDI', 1);
INSERT INTO `desa` VALUES (10, ' KARANG LANGIT', 1);
INSERT INTO `desa` VALUES (11, ' HARINGEN', 1);
INSERT INTO `desa` VALUES (12, ' JAWETEN', 1);
INSERT INTO `desa` VALUES (13, ' MATARAH', 1);
INSERT INTO `desa` VALUES (15, ' MARAGUT', 1);
INSERT INTO `desa` VALUES (16, ' MANGKARAP', 1);
INSERT INTO `desa` VALUES (17, ' GUMPA', 1);
INSERT INTO `desa` VALUES (18, ' SUMUR', 1);
INSERT INTO `desa` VALUES (19, ' HARARA', 1);
INSERT INTO `desa` VALUES (20, '-', 2);
INSERT INTO `desa` VALUES (21, ' KANDRIS', 2);
INSERT INTO `desa` VALUES (22, ' BANYU LANDAS', 2);
INSERT INTO `desa` VALUES (23, ' BAGOK', 2);
INSERT INTO `desa` VALUES (24, ' BAMBAN', 2);
INSERT INTO `desa` VALUES (25, ' TEWAH PUPUH', 2);
INSERT INTO `desa` VALUES (26, ' GUDANG SENG', 2);
INSERT INTO `desa` VALUES (27, ' PULAU PANDANG', 3);
INSERT INTO `desa` VALUES (28, ' KAMBINTIN', 3);
INSERT INTO `desa` VALUES (29, ' RAMANIA', 3);
INSERT INTO `desa` VALUES (30, ' BENTOT', 3);
INSERT INTO `desa` VALUES (31, ' AMPARI BURA', 3);
INSERT INTO `desa` VALUES (32, ' KOTAM', 3);
INSERT INTO `desa` VALUES (33, ' TAMIANG', 3);
INSERT INTO `desa` VALUES (34, ' BETANG NALONG', 3);
INSERT INTO `desa` VALUES (35, ' MUANI', 3);
INSERT INTO `desa` VALUES (36, ' JANGO', 3);
INSERT INTO `desa` VALUES (38, ' LALAP', 3);
INSERT INTO `desa` VALUES (39, ' JANAH JARI', 4);
INSERT INTO `desa` VALUES (40, ' BANGKIRAYEN', 4);
INSERT INTO `desa` VALUES (41, ' HAYAPING', 4);
INSERT INTO `desa` VALUES (42, ' TANGKAN', 4);
INSERT INTO `desa` VALUES (43, ' WUNGKUR NANAKAN', 4);
INSERT INTO `desa` VALUES (44, ' AMPARI', 4);
INSERT INTO `desa` VALUES (45, ' AMPAR BATU', 4);
INSERT INTO `desa` VALUES (46, ' BIWAN', 4);
INSERT INTO `desa` VALUES (47, ' JANAH MANSIWUI', 4);
INSERT INTO `desa` VALUES (48, ' DANAU', 4);
INSERT INTO `desa` VALUES (49, ' PIANGGU', 4);
INSERT INTO `desa` VALUES (51, ' DAMBUNG', 5);
INSERT INTO `desa` VALUES (52, ' SAING', 5);
INSERT INTO `desa` VALUES (53, ' RODOK', 5);
INSERT INTO `desa` VALUES (54, ' AMPAH DUA', 5);
INSERT INTO `desa` VALUES (55, ' PUTAI', 5);
INSERT INTO `desa` VALUES (56, ' NETAMPIN', 5);
INSERT INTO `desa` VALUES (57, ' SUMBER GARONGGONG', 5);
INSERT INTO `desa` VALUES (58, ' MUARA AWANG', 5);
INSERT INTO `desa` VALUES (59, ' MUARA PALANTAU', 6);
INSERT INTO `desa` VALUES (60, ' KETAB', 6);
INSERT INTO `desa` VALUES (61, ' KUPANG BERSIH', 6);
INSERT INTO `desa` VALUES (62, ' TUYAU', 6);
INSERT INTO `desa` VALUES (63, ' PINANG TUNGGAL', 6);
INSERT INTO `desa` VALUES (64, ' NAGA LEAH', 6);
INSERT INTO `desa` VALUES (65, ' LAMPEONG', 6);
INSERT INTO `desa` VALUES (66, ' BARARAWA', 6);
INSERT INTO `desa` VALUES (67, ' BAMBULUNG', 6);
INSERT INTO `desa` VALUES (68, ' LEBU', 6);
INSERT INTO `desa` VALUES (69, ' MURU DUYUNG', 6);
INSERT INTO `desa` VALUES (70, ' TUMPUNG ULUNG', 6);
INSERT INTO `desa` VALUES (71, ' SUMBEREJO', 6);
INSERT INTO `desa` VALUES (72, ' JURU BANU', 7);
INSERT INTO `desa` VALUES (73, ' TELANG BARU', 7);
INSERT INTO `desa` VALUES (74, ' TAMPULANGIT', 7);
INSERT INTO `desa` VALUES (75, ' TELANG', 7);
INSERT INTO `desa` VALUES (76, ' MAIPE', 7);
INSERT INTO `desa` VALUES (77, ' MARUTUWU', 7);
INSERT INTO `desa` VALUES (78, ' BALAWA', 7);
INSERT INTO `desa` VALUES (79, ' KALI NAPU', 7);
INSERT INTO `desa` VALUES (80, ' SIONG', 7);
INSERT INTO `desa` VALUES (81, ' PURI', 8);
INSERT INTO `desa` VALUES (82, ' LENGGANG', 8);
INSERT INTO `desa` VALUES (83, ' BATUAH', 8);
INSERT INTO `desa` VALUES (84, ' UNSUM', 8);
INSERT INTO `desa` VALUES (85, ' BARUYAN', 8);
INSERT INTO `desa` VALUES (86, ' TURAN AMIS', 8);
INSERT INTO `desa` VALUES (87, ' MALINTOT', 8);
INSERT INTO `desa` VALUES (88, ' TANGKUM', 8);
INSERT INTO `desa` VALUES (89, ' SIBUNG', 8);
INSERT INTO `desa` VALUES (90, ' TAMPA', 9);
INSERT INTO `desa` VALUES (91, ' KALAMUS', 9);
INSERT INTO `desa` VALUES (92, ' SIMPANG BINGKUANG', 9);
INSERT INTO `desa` VALUES (93, ' PATUNG', 9);
INSERT INTO `desa` VALUES (94, ' RUNGGU RAYA', 9);
INSERT INTO `desa` VALUES (95, ' BANTAI NAPU', 9);
INSERT INTO `desa` VALUES (96, ' TARINGSING', 9);
INSERT INTO `desa` VALUES (97, ' PAKU BETO', 9);
INSERT INTO `desa` VALUES (98, ' GANDRUNG', 9);
INSERT INTO `desa` VALUES (99, ' PANGKAN', 9);
INSERT INTO `desa` VALUES (100, ' KUPANG BARU', 9);
INSERT INTO `desa` VALUES (101, ' LUAU JAWUK', 9);
INSERT INTO `desa` VALUES (102, ' DAYU', 10);
INSERT INTO `desa` VALUES (103, ' WURAN', 10);
INSERT INTO `desa` VALUES (104, ' IPU MEA', 10);
INSERT INTO `desa` VALUES (105, ' LAGAN', 10);
INSERT INTO `desa` VALUES (106, ' PUTUT TAWULUH', 10);
INSERT INTO `desa` VALUES (107, ' SIMPANG NANENG', 10);
INSERT INTO `desa` VALUES (108, ' KANDRIS', 10);

SET FOREIGN_KEY_CHECKS = 1;
